test

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -12,11 +12,6 @@ if [ "$STACK" != "heroku-16" ] && [ "$STACK" != "heroku-18" ]; then
 	exit 1
 fi
 
-if [ -z "${PROCFILE_PATH}" ]; then
-	echo "PROCFILE_PATH is required. Set environment variable in the heroku app."
-	exit 1
-fi
-
 ### Configure directories
 BUILD_DIR=${1:-}
 CACHE_DIR=${2:-}
@@ -37,6 +32,11 @@ export DOTNET_CLI_TELEMETRY_OPTOUT=${DOTNET_CLI_TELEMETRY_OPTOUT:-1}
 DOTNET_SDK_VERSION=${DOTNET_SDK_VERSION:-3.1.407}
 DOTNET_RUNTIME_VERSION=${DOTNET_RUNTIME_VERSION:-3.1.13}
 BUILD_CONFIGURATION=${BUILD_CONFIGURATION:-Release}
+
+if [ -z "${PROCFILE_PATH}" ]; then
+	echo "PROCFILE_PATH is required. Set environment variable in the heroku app."
+	exit 1
+fi
 
 echo "Installing dotnet"
 install_dotnet $BUILD_DIR $CACHE_DIR $DOTNET_SDK_VERSION $DOTNET_RUNTIME_VERSION
