Netcoreapp31 clean release and sdk test (#5)
* declaring variable

* explicit PROCFILE_PATH

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -24,7 +24,7 @@ cp $BP_DIR/profile/* $BUILD_DIR/.profile.d/
 ### Load dependencies
 source $BP_DIR/lib/utils
 
-export_env_dir "$ENV_DIR"
+export_env_dir ${ENV_DIR}
 export NUGET_XMLDOC_MODE=${NUGET_XMLDOC_MODE:-skip}
 export DOTNET_SKIP_FIRST_TIME_EXPERIENCE=${DOTNET_SKIP_FIRST_TIME_EXPERIENCE:-1}
 export DOTNET_CLI_TELEMETRY_OPTOUT=${DOTNET_CLI_TELEMETRY_OPTOUT:-1}
@@ -33,6 +33,19 @@ DOTNET_SDK_VERSION=${DOTNET_SDK_VERSION:-3.1.407}
 DOTNET_RUNTIME_VERSION=${DOTNET_RUNTIME_VERSION:-3.1.13}
 BUILD_CONFIGURATION=${BUILD_CONFIGURATION:-Release}
 PROCFILE_PATH=${PROCFILE_PATH:-${BUILD_DIR}/Procfile}
+
+if [ -z "${PROCFILE_PATH}" ]; then
+	echo "PROCFILE_PATH is required. Set environment variable in the heroku app."
+	exit 1
+else
+	PROCFILE_PATH=${BUILD_DIR}/${PROCFILE_PATH}
+	echo ${PROCFILE_PATH}
+fi
+
+if ! [ -f ${PROCFILE_PATH} ]; then
+	echo "${PROCFILE_PATH} file does not exist. Please add it to repo."
+	exit 1
+fi
 
 echo "Installing dotnet"
 install_dotnet $BUILD_DIR $CACHE_DIR $DOTNET_SDK_VERSION $DOTNET_RUNTIME_VERSION
@@ -89,16 +102,5 @@ fi
 echo "Cleanup dotnet SDK"
 cleanup_dotnet $BUILD_DIR
 
-if [ -z "$PROCFILE_PATH:-" ]; then
-	echo "Using Procfile specified by PROCFILE_PATH: $PROCFILE_PATH" | indent
-	cp ${PROCFILE_PATH} ${BUILD_DIR}/Procfile
-else
-	if [ -f ${BUILD_DIR}/Procfile ] && grep -q '^web:' ${BUILD_DIR}/Procfile && [ ${PROJECT_FILE_OVERRIDES_PROCFILE:-false} = "false" ] ; then
-		echo "Using ${BUILD_DIR}/Procfile" | indent
-	else
-		first_project_name=$(basename ${proj[0]%.*})
-		echo "Auto-generating Procfile"
-		echo "Add web process to Procfile $first_project_name" | indent
-		echo -e "web: cd \$HOME/heroku_output/${first_project_name} && ./${first_project_name}" > ${BUILD_DIR}/Procfile
-	fi
-fi
+cp ${PROCFILE_PATH} ${BUILD_DIR}/Procfile
+echo "Using Procfile specified by PROCFILE_PATH: $PROCFILE_PATH" | indent
