Support for multiple test projects

diff --git a/bin/test b/bin/test
--- a/bin/test
+++ b/bin/test
@@ -22,10 +22,20 @@ export DOTNET_CLI_TELEMETRY_OPTOUT=${DOTNET_CLI_TELEMETRY_OPTOUT:-1}
 
 export PATH="${DOTNET_SDK_LOCATION}:${PATH}"
 
-if [ -z ${TEST_PROJECT_FILE:-} ]; then
-	TEST_PROJECT_FILE=$(find ${BUILD_DIR} -maxdepth 5 -name *.csproj -exec grep -l -H 'Microsoft.NET.Test.Sdk' {} \;)
-fi
+find_test_projects $BUILD_DIR
 
-echo "run tests in ${TEST_PROJECT_FILE}"
+echo -e "2Found test projects:\n$TEST_PROJECTS"
 
-dotnet test -v q --no-build --no-restore $TEST_PROJECT_FILE
+# keep track of error codes from all commands
+# (this script must exit with a nonzero error code if ANY command exits with nonzero)
+declare -i EXIT_CODE # == 0
+
+# run each discovered test project
+while IFS= read -r filename
+  do
+    echo "run: $filename"
+    dotnet test -v q --no-build --no-restore --configuration Release $filename
+    EXIT_CODE+=$?
+done <<< $TEST_PROJECTS
+
+exit $EXIT_CODE
diff --git a/bin/test-compile b/bin/test-compile
--- a/bin/test-compile
+++ b/bin/test-compile
@@ -14,12 +14,26 @@ BP_DIR=$(cd $(dirname ${0:-}); cd ..; pwd)
 
 cd $BUILD_DIR
 
-if [ -z ${TEST_PROJECT_FILE:-} ]; then
-	TEST_PROJECT_FILE=$(find ${BUILD_DIR} -maxdepth 5 -name *.csproj -exec grep -l -H 'Microsoft.NET.Test.Sdk' {} \;)
-fi
+find_test_projects $BUILD_DIR
 
-export PROJECT_FILE=${TEST_PROJECT_FILE}
-export BUILD_CONFIG=Debug
-export BUILD_PUBLISH="false"
+echo -e "2Found test projects:\n$TEST_PROJECTS"
 
-$BP_DIR/bin/compile "$1" "$2" "$3"
+# keep track of error codes from all commands
+# (this script must exit with a nonzero error code if ANY command exits with nonzero)
+declare -i EXIT_CODE # == 0
+
+# run each discovered test project
+while IFS= read -r filename
+  do
+    echo "build: $filename"
+
+    export PROJECT_FILE=$filename
+    export BUILD_CONFIG=Debug
+    export BUILD_PUBLISH="false"
+
+    $BP_DIR/bin/compile "$1" "$2" "$3"
+
+    EXIT_CODE+=$?
+done <<< $TEST_PROJECTS
+
+exit $EXIT_CODE
